### ISSUE TITLE
P3: Un-American spelling

### ISSUE THREAD

**Issue by jessetipton** [MakeSchool-Tutorials/Makestagram-Swift-V2#1]
This might be pedantic, but there's a section in step 3 title "Modelling Object Relationships". While not technically incorrect, the single-L version of the word "modeling" is more common. (via http://grammarist.com/spelling/model/)

**Comment by dionlarson** [comment]
You'll find a few of these throughout the tutorials -- quite a few of our curriculum writers over time have been European. Definitely point them out! It's better for us to be consistent.

**Comment by danielhaaser** [comment]
Fixed in df2768a00d445b5f6458e3a8cbec7a98c55ebf1b
