### ISSUE TITLE
5. after updating the starter project, now missing instructions for which pods to add

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Makestagram-Swift-V2#12]
the web tutorial goes straight from `pod init` to `pod install` without specifying which pods should be added to the empty podfile

**Comment by danielhaaser** [comment]
I don't see what you're seeing
<img width="854" alt="screen shot 2016-06-13 at 11 49 07 am" src="https://cloud.githubusercontent.com/assets/1690436/16019255/e583b1f6-315c-11e6-86c6-b7ab69c299d3.png">

Feel free to reopen this issue if I'm mistaken.
