### ISSUE TITLE
variable should be declared first in tutorial

### ISSUE THREAD

**Issue by wustladela** [MakeSchool-Tutorials/Makestagram-Swift-V2#13]
var posts: [Post] = []
var photoTakingHelper: PhotoTakingHelper?
var photoUploadTask: UIBackgroundTaskIdentifier?

these 3 variables are declared after usage which could potentially be confusing for some people, as they would try to think "where did I declare this variable?"

**Comment by djh-** [comment]
Fixed in 2cf8a1944ea2a66339263196ba45904a71b05477

**Comment by danielhaaser** [comment]
Fixed in 86e1dc30021c2fcd12457042da1bb58bc147b469
