### ISSUE TITLE
Cocoapods Install Takes a Long Time

### ISSUE THREAD

**Issue by danielhaaser** [MakeSchool-Tutorials/Makestagram-Swift-V2#15]
Write a comment about how it might take a long time the first time you run `pod install`

**Comment by cliffweitzman** [comment]
It takes about 10 minutes. If you want to make sure something is working you can go to activity monitor open the network tab and search for "http." This may have good data on getting pods to download faster though idk if these work http://stackoverflow.com/questions/21680573/cocoapods-setup-stuck-on-pod-setup-command-on-terminal

**Comment by danielhaaser** [comment]
Fixed in e2c7ff8463e4abb8c775f8373fed8e24fd8a60e5
