### ISSUE TITLE
P08 order of instructions

### ISSUE THREAD

**Issue by Frostao** [MakeSchool-Tutorials/Makestagram-Swift-V2#16]
I feel like when the following instruction was presented in a wrong order.

``` swift
if viewController is PhotoViewController {
        takePhoto()
        return false
    } else {
        return true
}
```

The function takePhoto() should be presented before or together with this code. It makes some people(like me) ask questions to their instructors right away. Also the property declaration should be presented before.

**Comment by danielhaaser** [comment]
Half fixed in 2cf8a1944ea2a66339263196ba45904a71b05477

I moved the property declaration earlier, but left the `takePhoto()` declaration for later. It takes a lot of time to explain what's happening in `takePhoto()` because of closures, so I feel like it's better to order it that way.
