### ISSUE TITLE
P09 image upload without a name

### ISSUE THREAD

**Issue by Frostao** [MakeSchool-Tutorials/Makestagram-Swift-V2#17]
``` swift
let imageFile = PFFile(name: "image.jpg", data: imageData)!
```

The above initializer should be used such that Parse will not name the image *.bin. If we use the above method, we can view the upload directly.
Also,

``` swift
imageFile.saveInBackground()
```

is not necessary because when you call 

``` swift
post.saveInBackground()
```

, the imageFile will be uploaded.

**Comment by danielhaaser** [comment]
Fixed in 4f9bd72f1d206d384363aeded761fa3d67e2db78
