### ISSUE TITLE
P10 background task code should be in a different place

### ISSUE THREAD

**Issue by Frostao** [MakeSchool-Tutorials/Makestagram-Swift-V2#18]
``` swift
UIApplication.sharedApplication().endBackgroundTask(self.photoUploadTask!)
```

Should be in the block of the PFObject not the PFFile upload block. Because when saving PFObject, PFFile is also saved in the process.

**Comment by danielhaaser** [comment]
Fixed in 28f8a7552727d56cee3f8766945d1356cde8cec6
