### ISSUE TITLE
1. Setting up Parse on Heroku – Payment Information 

### ISSUE THREAD

**Issue by ocwang** [MakeSchool-Tutorials/Makestagram-Swift-V2#2]
In the section, _Setting up Parse Server_, after step 8, Heroku won't let me continue unless I verify my account by entering payment information.

Both the _Setting up Heroku_ and _Setting up Parse Server_ don't mention anything about entering credit card information.

**Comment by dionlarson** [comment]
Working on this -- trying to get credits from Heroku and avoid this process (at least for SA).

**Comment by dionlarson** [comment]
Closing this for preference towards an issue on the Heroku setup tutorial. https://github.com/MakeSchool-Tutorials/Parse-Server-Setup/issues/2
