### ISSUE TITLE
PhotoHelper File

### ISSUE THREAD

**Issue by cliffweitzman** [MakeSchool-Tutorials/Makestagram-Swift-V2#21]
![image](https://cloud.githubusercontent.com/assets/3460171/16067615/028e3fd4-3273-11e6-83c5-b423f3f52af3.png)

When I create the PhotoHelper folder in finder and then add it to the project it appears as blue. If I then try to add a file to it, it does not pop up the xcode screen for choosing between coco touch and swift etc. it just creates a generic file. not sure why. It does work if I merely add a folder in xcode but not finder.

**Comment by danielhaaser** [comment]
When you right click --> add files to Makestagram there's a small options button at the bottom of the dialogue that pops up. Expand those options and select "Create Groups" instead of "Create Folder References"

**Comment by cliffweitzman** [comment]
Thanks! That works. We should add that to the tutorial

**Comment by danielhaaser** [comment]
Fixed in 978ff6f0857c5c0da742edba27b26d9f011e9829
