### ISSUE TITLE
5. Setting up the Xcode Project / CocoaPods – XCode Can't Locate Header Files

### ISSUE THREAD

**Issue by ocwang** [MakeSchool-Tutorials/Makestagram-Swift-V2#23]
I can't seem to figure out the following issue. I've followed the instructions in the tutorial line by line, but after I update my Podfile and run `pod install` I can't get my app to compile or run because it's having problem finding FBSDKCoreKit header files.

![image](https://cloud.githubusercontent.com/assets/5977858/16069351/8ffe6308-3282-11e6-995f-5d709acbf7da.png)

I've tried the following:
1. Deleting the whole project folder, re-downloading the starter project and re-following steps on the tutorial multiple times
2. Manually downloading the FBSDKCoreKit framework and placing it within the workspace
3. Setting `Allows Non-modular In Framework Modules` from NO to Yes in Build Settings, removing `use_frameworks!` in the Podfile, downgraded my ParseFacebookUtilsV4 pod to 1.8.5 (can't because Parse requires 1.9.0)

I think that I have to be missing something if I'm the only instructor running into this error, I'll check with everyone else and compare to see if I can find any differences in build settings.

This bug is also referenced in: ParsePlatform/ParseFacebookUtils-iOS#2

**Comment by danielhaaser** [comment]
I would try deleting the derived data (Window --> Projects --> Delete) and rebuilding, maybe that will help?

**Comment by ocwang** [comment]
Yeah, I've tried deleting derived data after making changes. Hasn't worked yet. I imagine it's some obscure bug in my Build Settings that's different from everyone else.

**Comment by danielhaaser** [comment]
Your Xcode is the latest version?

**Comment by ocwang** [comment]
Yeah, just re-checked and it's 7.3.1.

**Comment by danielhaaser** [comment]
I assume you tried redownloading the starter project also?  I just tried it and it worked fine on my computer. I'm pretty lost at this point.

**Comment by danielhaaser** [comment]
Oh, what's your cocoapods version? I'm on 1.0.1. Using system Ruby.

**Comment by ocwang** [comment]
Yeah, unfortunately tried that multiple times with no success. Cocoapods version is 1.0.1.

**Comment by danielhaaser** [comment]
Here's the version I just `pod install`ed, does it work for you?

[Makestagram-Swift-V2-Starter-pods-installed.zip](https://github.com/MakeSchool-Tutorials/Makestagram-Swift-V2/files/316665/Makestagram-Swift-V2-Starter-pods-installed.zip)

**Comment by ocwang** [comment]
That project worked!
