### ISSUE TITLE
18. suggestion to put `func stringFromUserList(userList: [PFUser]) -> String` in a helper class instead of having it in `PostTableViewCell`

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Makestagram-Swift-V2#26]
suggestion to put `func stringFromUserList(userList: [PFUser]) -> String` in a helper class instead of having it in `PostTableViewCell`

**Comment by danielhaaser** [comment]
Generally I would prefer to leave it in `PostTableViewCell` until the point where another class needs the same functionality, at which point I would put it in a helper class.  I thought about trying to explain that in the tutorial, but I think it would distract from the other content.
