### ISSUE TITLE
19. type in section "Incorporating the TimelineComponent"

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Makestagram-Swift-V2#27]
In the sentence 

> We can ignore the typealias, which leaves use with four requirements for classes that implement the TimelineComponentTarget protocol:

**use** should be **us**:

> We can ignore the typealias, which leaves **us** with four requirements for classes that implement the TimelineComponentTarget protocol:

**Comment by danielhaaser** [comment]
Fixed in cd2a66120a6f40407a672f63c81c5add2db916dc
