### ISSUE TITLE
19. is there a reason why the TimelineComponentTarget protocol is not implemented in an extension of TimelineViewController?

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Makestagram-Swift-V2#28]
just came to my mind as all other protocol implementations that have been done so far were in a class extension, so just wondering about this...

**Comment by danielhaaser** [comment]
Yep, extensions cannot contain stored properties, and the `TimelineComponentTarget` protocol requires us to define two of them, `defaultRange` and `additionalRangeSize`.
