### ISSUE TITLE
5.: Starter Project already contains Podfile including dependencies

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Makestagram-Swift-V2#3]
The [Start Project](https://github.com/MakeSchool/Makestagram-Swift2/archive/xcode7_starter_project.zip) already contains a Podfile including dependencies, but a bit later after downloading it the tutorial says to navigate to the root directory of the project and use `pod init` and then configure the podfile yourself.

**Comment by nikolasburk** [comment]
the .xcworkspace is also already there in the starter project, so not sure if running `pod install` is required again at all

**Comment by ocwang** [comment]
@nikolasburk The actual Pods workspace is missing until you run `pod install`, so yes you do have to run `pod install`, otherwise the compiler will throw missing file errors.

**Comment by danielhaaser** [comment]
Fixed in MakeSchool-Tutorials/Makestagram-Swift-V2-Starter@2e7df6b6163c073228922f2b71e9dbf6ae89c5ac
