### ISSUE TITLE
P9 - Viewing image in Parse (Heroku) - does not show image -

### ISSUE THREAD

**Issue by MichaelMeinberg** [MakeSchool-Tutorials/Makestagram-Swift-V2#31]
It downloads a ".bin" file which, if you want, you can see in Finder if you use the expanded view.  
![screen shot 2016-06-15 at 4 26 35 pm](https://cloud.githubusercontent.com/assets/4966291/16100832/feb217b6-3315-11e6-8996-2c168f62c6c5.png)

**Comment by danielhaaser** [comment]
This is actually fixed in the latest version of the tutorial!  Now to make sure it's updated on the summer academy site...
