### ISSUE TITLE
10. Improving the Upload Code and Adding a Post Class

### ISSUE THREAD

**Issue by rnkorneeva** [MakeSchool-Tutorials/Makestagram-Swift-V2#37]
Hello! I am at this step in tutorial. And when I added Post.swift file during following this step my app just show me this message:
![screen shot 2016-07-24 at 15 00 03](https://cloud.githubusercontent.com/assets/20534740/17083623/b8522aa2-51b7-11e6-8af4-cc8c5e07999c.png)
So, I think that it's not my mistake and there is a problem in code in tutorial.
Thank you

**Comment by rnkorneeva** [comment]
```
override class func initialize() {
        var onceToken : dispatch_once_t = 0;
        dispatch_once(&onceToken) {
            // inform Parse about this subclass
            self.registerSubclass()
        }
```

I found out that it works without these lines of code =)

**Comment by danielhaaser** [comment]
Yep!
