### ISSUE TITLE
Set up your own Parse server – Debugging Tip

### ISSUE THREAD

**Issue by ocwang** [MakeSchool-Tutorials/Makestagram-Swift-V2#4]
I setup my Parse Server / Dashboard exactly as described by the instructions in _Set up your own Parse server_ tutorial, but when I opened my dashboard, it said that my server was unavailable / unauthorized like below:

![image](https://cloud.githubusercontent.com/assets/5977858/15994504/529d4614-30bb-11e6-9f5c-188125e34362.png)

Turns out that even through I set my APP_ID, MASTER_KEY, SERVER_URL correctly, Heroku didn't register my input and kept it's (Heroku's) default values as my config vars. To fix this you can go to Heroku dashboard > click on your Parse Server / Dashboard Apps > Settings > Reveal Config Vars and make sure that your Config Vars are properly set.

Another debugging solution would be to delete your Parse Server / Dashboard and follow the instructions outlined in _Set up your own Parse server_ again.

It could be helpful in the tutorials for students to have these debugging tips (in case they run into these issues.)

**Comment by danielhaaser** [comment]
I didn't run into this issue, so I'm not sure how to write the instructions to work around it. Can you open a pull request on this repo https://github.com/MakeSchool-Tutorials/Parse-Server-Setup with the instructions?
