### ISSUE TITLE
CocoaPods problems

### ISSUE THREAD

**Issue by jessetipton** [MakeSchool-Tutorials/Makestagram-Swift-V2#5]
After downloading the starter project and running `pod install` I was having an issue importing dependencies that should have been included through CocoaPods.

<img width="1040" alt="screen shot 2016-06-12 at 4 27 34 pm" src="https://cloud.githubusercontent.com/assets/2132778/15994541/4aa1f3aa-30bc-11e6-997c-9546aa8a2cf5.png">

`pod install` ended its output with these warnings:

<img width="822" alt="screen shot 2016-06-12 at 4 35 48 pm" src="https://cloud.githubusercontent.com/assets/2132778/15994544/7e9b721c-30bc-11e6-96e6-8f3bc3015f7c.png">

I replaced what was in the `Framework Search Paths` build setting for both targets with `$(inherited)` and that fixed the import issue.

**Comment by ocwang** [comment]
To build on the screenshot that @jessetipton shared, Cocoapods is also complaining about the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting. Similarly, I fixed the issue by going to Build Settings > Searching for `Embedded Content Contains Swift Code` > Clicking on the value, selecting the other option from the drop down, and inserting `$(inherited)`.

![image](https://cloud.githubusercontent.com/assets/5977858/15994885/0b37e838-30c5-11e6-95cf-e9af3d49a71e.png)

Afterwards, you can confirm that there are no longer errors by running `pod install` from the root directory of the project.

**Comment by danielhaaser** [comment]
Fixed in MakeSchool-Tutorials/Makestagram-Swift-V2-Starter@13e186a45bd9d8bcff5c781ba8d144ad0681e47d
