### ISSUE TITLE
6. needs more markup formatting

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Makestagram-Swift-V2#8]
In the first section, the following code is shown without formatting:

let configuration = ParseClientConfiguration { (configuration) -> Void in configuration.applicationId = "parseAppOne2" configuration.server = "https://parsepass1.herokuapp.com/parse" }

**Comment by nikolasburk** [comment]
also, when mentioning "$0", markdown formatting should be used as well

**Comment by danielhaaser** [comment]
Fixed in 548fe8d77e8948a7d7af885630f13190e054e484
