### ISSUE TITLE
Parse-dashboard version is not up to date.

### ISSUE THREAD

**Issue by Frostao** [MakeSchool-Tutorials/Makestagram-Swift-V2#9]
I forked the repo and made the change to the version. You guys can use mine.
[url](https://github.com/Frostao/parse-dashboard-heroku)

**Comment by danielhaaser** [comment]
Updated in MakeSchool-Tutorials/Parse-Server-Setup@21cff71b21ff7d78d0d8d8312eaf2f6d4c2c02f4 thanks.
